Sammy dev
Ciela-Institute/PQM pull request #9
Opened 2024-05-31 18:54 UTC by SammyS15

2024-07-18 21:15 UTC, SammyS15 reviewed
Updated bootstrap to re_tessellation

2024-07-19 02:02 UTC, ConnorStoneAstro requested changes
Looks great! I just have one minor change to the notebooks and a question. I don't feel 100% confident in the p-value accept/reject null stuff so I'd rather we just remove it and let users decide what to do.

2024-07-19 02:02 UTC, ConnorStoneAstro commented on README.md
>  If your two samples are drawn from the same distribution, then the p-value should
just double checking, in this paragraph you say the peak is at DoF - 2, is that right or is it DoF - 1?

2024-07-19 13:39 UTC, ConnorStoneAstro approved these changes

2024-07-19 13:43 UTC, merged